---

summary_host: testuppmax
summary_user: arteria
summary_host_key: /path/to/ssh/key
summary_destination: /tmp/summaries/
summary_ngi_pipeline_reports_destination: /tmp/summaries/ngi_reports

projman_install_location: /path/to/projman_filler
projman_connection_string: mssql+pymssql://<username>:<password>@<host>/<database>?charset=utf8

biotank_hosts: mm-xart002,mm-xart003
biotank_user: arteria
biotank_user_key: "/path/to/ssh/key"
# the path to the archive folder, relative to the /data/biotankX/ folder
biotank_archive_folder: relative/path/to/archive/folder
days_to_keep_archived_runfolder: 30
samplesheet_fallback_path: /path/to/samplesheet/fallback/location

remote_host: testuppmax
remote_user: arteria
remote_host_key: /path/to/ssh/key
remote_destination: /tmp/runfolders/
remote_sisyphus_location: /opt/arteria/arteria-siswrap-env/deps/sisyphus/sisyphus-latest

ngi_pipeline_url: https://irma1.uppmax.uu.se:4444/ngi_pipeline_upps

irma_api_key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaa
irma_remote_path: ./staging/
irma_reports_remote_path: ./staging/reports/
irma_summary_ssh_user: user
irma_summary_ssh_key: /path/to/ssh/key
irma_summary_ssh_cert: /path/to/ssh/cert
irma_summary_host: irma1.uppmax.uu.se
irma_checksum_base_url: https://irma1.uppmax.uu.se:4444/arteria_checksum_staging/api/1.0
irma_siswrap_base_url: https://irma1.uppmax.uu.se:4444/arteria_siswrap_staging/api/1.0
irma_archive_upload_base_url: https://irma1.uppmax.uu.se:4444/arteria_archive_staging/api/1.0
archive_db_base_url: http://mm-xart002:10500/api/1.0/
delivery_service_url: http://some-host.com:9999/
archive_verify_base_url: http://mm-xart002:10400/api/1.0/

# Number of days we want to look back when picking an unverified but
# uploaded archive. The exact time period will be adjusted by the safety
# margin setting as well though.
archive_db_verify_lookback_window: 7

# Safety margin (days) when checking for an unverified but uploaded archive.
# The margin is meant to ensure that we're not verifying something that PDC
# still keeps on disk - instead it should have been flushed to tape.
archive_db_verify_safety_margin: 3

irma_replace_expressions:
 - 's/UPPNEX_PROJECT: a2009002/UPPNEX_PROJECT: ngi2016001/'
 - 's/UPPNEX_QOS: seqver/#UPPNEX_QOS: seqver/'

send_mail_to: example.mail.address@send.errors.to

runfolder_service_port: 10800
bcl2fastq_service_port: 10900
siswrap_service_port: 10700
checkqc_service_port: 11000
archive_upload_service_port: 10600
archive_remove_service_port: 10300

# The service URL polled in the runfolder sensor:
runfolder_svc_urls:
  - http://testarteria1:10800/api/1.0/runfolders/pickup

incoming_svc_urls:
  - url: http://testarteria1:10850/api/1.0/runfolders/next
    dest_folder: /data/testarteria1/runfolders
    remote_user: arteria
    user_key: /home/arteria/.ssh/id_rsa


charon_api_token: dummy_token
charon_base_url: http://charon.url
slack_webhook_url: https://slack.webhook.url
# proxy to use when posting to slack
slack_proxy_url:

charon_status_report_slack_channel: "#bottest"
check_cert_slack_channel: "#bottest"
delivery_workflow_status_slack_channel: '#bottest'
archive_status_slack_channel: "#bottest"

supr_api_user: apiuser
supr_api_key: apikey
supr_api_url: https://disposer.c3se.chalmers.se/supr-test/api
